In [1]:
import torch

In [7]:
x = torch.rand((2, 3), requires_grad=True)
x

tensor([[0.4611, 0.5443, 0.0322],
        [0.1328, 0.1979, 0.7267]], requires_grad=True)

In [9]:
y = torch.sum(x**2 + torch.exp(x))
y.backward()

In [10]:
x.grad

tensor([[2.5080, 2.8119, 1.0970],
        [1.4075, 1.6146, 3.5214]])

In [ ]:
torch.Tensor

tensor([2.])

In [16]:
from mytorch import Tensor
import numpy as np

In [20]:
print(Tensor([[1, 2, 3], [1, 2, 3]]))

tensor([[1 2 3]
 [1 2 3]])


In [ ]:
def f():

    return 1, 2

x, y = *f()

SyntaxError: can't use starred expression here (3531793059.py, line 5)

In [1]:
def f(*x):
    print(x)

f(1)

(1,)
